apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-dxlk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-dxlk
    app.kubernetes.io/part-of: tkrw-pr712-0075-0013-app
  name: devfile-sample-dxlk
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-dxlk
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-dxlk
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0013-tenant/tkrw-pr712-0075-0013-app/devfile-sample-dxlk@sha256:c910ccfc73aacb7b81f364de8b292efa90ae30117a4ad70af9edc41dc850f436
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
